name: Build & Tests

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel: [ "stable", "nightly" ]

    continue-on-error: ${{ matrix.channel == 'nightly' }}
    name: Build & Test (${{ matrix.channel }})

    steps:
    - uses: actions/checkout@v3

    - name: Setup ${{ matrix.channel }} Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: ${{ matrix.channel }}

    - name: ${{ matrix.channel }} build
      run: cargo +${{ matrix.channel }} build --verbose

    - name: ${{ matrix.channel }} tests
      run: cargo +${{ matrix.channel }} test --verbose
